### ISSUE TITLE
Error during compilation - "fatal error: 'cstdint' file not found"

### ISSUE THREAD

**Issue by joneidejohnsen** [vrasneur/pyfasttext#1]
Here's my output:
```
➜  pyfasttext git:(master) python3 setup.py install
Compiling src/pyfasttext.pyx because it changed.
[1/1] Cythonizing src/pyfasttext.pyx
running install
running build
running build_ext
building 'pyfasttext' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.6
creating build/temp.macosx-10.7-x86_64-3.6/src
creating build/temp.macosx-10.7-x86_64-3.6/src/fastText
creating build/temp.macosx-10.7-x86_64-3.6/src/fastText/src
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -iquote . -include src/custom_exit.h -I. -I/Users/xx/anaconda/include/python3.6m -c src/pyfasttext.cpp -o build/temp.macosx-10.7-x86_64-3.6/src/pyfasttext.o
In file included from <built-in>:1:
./src/custom_exit.h:14:61: error: no member named 'to_string' in namespace 'std'
  throw std::runtime_error("fastext tried to exit: " + std::to_string(status));
                                                       ~~~~~^
In file included from src/pyfasttext.cpp:488:
src/fastText/src/vector.h:13:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
2 errors generated.
error: command 'gcc' failed with exit status 1
```

Compiling the "normal" FastText binaries, as well as SaleStock's fastText.py works without any problems. Any thoughts on how to fix this?

**Comment by vrasneur** [comment]
Your default compiler (gcc) uses C++03 (or C++98) by default, not C++11.

I just need to add the "-std=c++11" parameter in the compiler cppflags.
fastText requires a C++11 compliant compiler anyway.

**Comment by vrasneur** [comment]
I use std::make_unique() in the Cython code, which is only available in C++14.

So, I have added "-std=c++14" to the command line.

Can you update your repository and try again?

**Comment by vrasneur** [comment]
Okay, I have reimplemented std::make_unique().

So, it should work now if you compile pyfasttext with the same compiler you used for fastText itself.

**Comment by joneidejohnsen** [comment]
I still experience errors during compilation with the newest commit, although a bit different than last time:

`➜  pyfasttext python3 setup.py install
running install
running build
running build_ext
building 'pyfasttext' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.6
creating build/temp.macosx-10.7-x86_64-3.6/src
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -iquote . -include src/custom_exit.h -I. -I/Users/xx/anaconda/include/python3.6m -c src/pyfasttext.cpp -o build/temp.macosx-10.7-x86_64-3.6/src/pyfasttext.o -std=c++0x -Wno-sign-compare
In file included from <built-in>:1:
./src/custom_exit.h:14:61: error: no member named 'to_string' in namespace 'std'
  throw std::runtime_error("fastext tried to exit: " + std::to_string(status));
                                                       ~~~~~^
src/pyfasttext.cpp:487:10: fatal error: 'fastText/src/vector.h' file not found
#include "fastText/src/vector.h"
         ^
2 errors generated.
error: command 'gcc' failed with exit status 1`

For reference, here's the version info of my compiler:
`➜  pyfasttext gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by vrasneur** [comment]
Have you used the "--recursive" parameter when you have cloned the repository?

`git clone --recursive https://github.com/vrasneur/pyfasttext.git`

If you do not use that, it will not retrieve the fastText source code.

For the "std::to_string()" error, it is strange, because this function is included in C++11. But this error should be fixed in the last commit.

Can you try again?

**Comment by joneidejohnsen** [comment]
My Anaconda Python 3.6 distribution was the cause of the problem, as it used its own outdated GCC compiler. Upgrading it with `conda install -c anaconda gcc=4.8.5` solved the issue.
